name: teacher
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.5.0
  shared_preferences: ^2.0.15
  flutter_colorpicker: ^1.1.0
  provider: ^6.1.2
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  table_calendar: ^3.1.2
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/XML/ders.xml
    - lib/XML/etkinlikler.xml

analyzer:
  errors:
    unused_import: ignore
    unused_local_variable: ignore
    prefer_const_constructors: ignore
