// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgwr11WZ-YsJ__M_atcAHsIRPRLBsfm9s',
    appId: '1:942966405362:web:519ce299191a11b04cf86b',
    messagingSenderId: '942966405362',
    projectId: 'teacherapp-8b032',
    authDomain: 'teacherapp-8b032.firebaseapp.com',
    databaseURL: 'https://teacherapp-8b032-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'teacherapp-8b032.appspot.com',
    measurementId: 'G-32EEMJHGGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmUeWOboxUXzJhrRXbxPpDG22RiFq4OkY',
    appId: '1:942966405362:android:8f90a1730df2a1cb4cf86b',
    messagingSenderId: '942966405362',
    projectId: 'teacherapp-8b032',
    databaseURL: 'https://teacherapp-8b032-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'teacherapp-8b032.appspot.com',
  );
}
