// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'YOUR_WEB_API_KEY',  // Replace with your Web API key
  appId: 'YOUR_WEB_APP_ID',  // Replace with your Web App ID
  messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',  // Replace with your Messaging Sender ID
  projectId: 'YOUR_PROJECT_ID',  // Replace with your Project ID
  authDomain: 'YOUR_AUTH_DOMAIN',  // Replace with your Auth Domain
  databaseURL: 'YOUR_DATABASE_URL',  // Replace with your Database URL
  storageBucket: 'YOUR_STORAGE_BUCKET',  // Replace with your Storage Bucket
  measurementId: 'YOUR_MEASUREMENT_ID',  // Replace with your Measurement ID
);

static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'YOUR_ANDROID_API_KEY',  // Replace with your Android API key
  appId: 'YOUR_ANDROID_APP_ID',  // Replace with your Android App ID
  messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',  // Replace with your Messaging Sender ID
  projectId: 'YOUR_PROJECT_ID',  // Replace with your Project ID
  databaseURL: 'YOUR_DATABASE_URL',  // Replace with your Database URL
  storageBucket: 'YOUR_STORAGE_BUCKET',  // Replace with your Storage Bucket
);
}
